# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DMSTask": "03_simplest_srnn_dms.ipynb",
         "SpatialDMSSimple": "03_simplest_srnn_dms.ipynb",
         "LDN": "04_lmu_dms.ipynb",
         "make_ldn_B_A": "04_lmu_dms.ipynb",
         "make_lmu_dms": "04_lmu_dms.ipynb",
         "logger": "05_lmu_dms_tuning.ipynb",
         "generate_default_params": "05_lmu_dms_tuning.ipynb",
         "run_trial": "05_lmu_dms_tuning.ipynb"}

modules = ["dms.py",
           "lmu.py",
           "tune/lmu_dms.py"]

doc_url = "https://neuromorphs.github.io/srnn_pfc/"

git_url = "https://github.com/neuromorphs/grill-srnn-pfc/tree/master/"

def custom_doc_links(name): return None
